### ISSUE TITLE
Red alert in recovery saved games.

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3345]
This happens sometimes and can be seen at the beginning of the video. You need to load it twice.
http://youtu.be/X_XE2xdpO5g
The video is from Pioneer Scout+, but this also happens in the Pioneer clean motor. I was lucky to capture it.

**Comment by fluffyfreak** [comment]
Did the comms window not work the first time? it's hard to tell.

**Comment by walterar** [comment]
When loading the first time: Red Alert. Exit and reload: Green Alert.

**Comment by walterar** [comment]
When the game was recorded, was in Green Alert (ALERT_NONE).
When he recovers, he is on Red Alert (ALERT_SHIP_FIRING). (incorrect)
I close and I reload, is on Green Alert (ALERT_NONE). (correct)

It is understood better now?

**Comment by nick-the-ninja** [comment]
This has happened for JSONSerialise branch too (not surprising - as JSONSerialise serialises exactly the same data).
The cause of this (and similar issues) will be much easier to track down with a JSON savegame file.

**Comment by walterar** [comment]
Yes, that's what I think. Use your weapons! :))

**Comment by impaktor** [comment]
@walterar was this bug fixed by #3355?

**Comment by walterar** [comment]
@Impaktor Fixed in Linux, not in Windows

**Comment by walterar** [comment]
Verified in latest version for Windows compiled by me with MXE and VS2013. The latest version for Windows published in http://sourceforge.net/projects/pioneerspacesim/files/pioneer-20150319-win32.7z/download not incorporate #3355

**Comment by fluffyfreak** [comment]
So @robn we need a new windows build doing then is what you're trying to say?

**Comment by nozmajner** [comment]
I mentioned this on IRC before, but let me note this here next to a build call. :)
The latest two windows builds (0314, 0319) are still showing 20150201(50c25a6) version number in the main menu, and and it seems that the new features (headlook for example) aren't showing up in them.

**Comment by robn** [comment]
Noted, I'll check as soon as I can.

**Comment by joonicks** [comment]
bug still present in 20150912 build (windows)
specifically I got it after exiting hyperspace, "laser fire detected" with nothing but me and my hyperspace cloud around.

**Comment by notinlist** [comment]
I see "laser fire detected" after loading a game. I travel to another solar system, I exit the hyperspace cloud and the warning is still present. I decide to do a save and load trick. I try to save the game and I get "JSON serializer '(null)' tried to serialize an invalid 'Ship' object". I get this or similar message quite often in other situations too, for example when entering a space station, just after landing when the welcome message used to appear. The same with "Lua serializer" used to happen there. Last time at Daniel's heaven. I suspect that this null ship serialization and the stuck "laser fire detected" warning are connected.

**Comment by notinlist** [comment]
This last thing (Going to Sol and then to Daniel's heaven and then landing) 100% reproduces the Lua ship serialization error.
[_autosave2.zip](https://github.com/pioneerspacesim/pioneer/files/116318/_autosave2.zip)

**Comment by sloanonlinux** [comment]
I hope this is a minor issue and doesn't bug the crap outta me

**Comment by impaktor** [comment]
@sloanonlinux did this just happen to you? On a recent version of pioneer?

**Comment by sloanonlinux** [comment]
> @sloanonlinux did this just happen to you? On a recent version of pioneer?
No

**Comment by limburgher** [comment]
I see the laser fire detected bug on 20160814.

**Comment by Fixer-007** [comment]
I see the laser fire detected bug on 20170827

**Comment by Fixer-007** [comment]
Here is autosave where you can reproduce this bug pretty easily in a few tries, load it, wait few seconds, press > 1x time acceleration:
[_autosave3.zip](https://github.com/pioneerspacesim/pioneer/files/1267231/_autosave3.zip)

**Comment by richardpl** [comment]
Does this still happens?

**Comment by limburgher** [comment]
Not on 20180203.

**Comment by richardpl** [comment]
Feel free to comment if this happens again.

**Comment by Fixer-007** [comment]
Was there attempt to fix this bug?

**Comment by richardpl** [comment]
I failed to reproduce it, but if you still can with latest version then say so.
