### ISSUE TITLE
Transparent backgrounds in screenshots

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4671]
Taking in-game screenshots (Ctrl+PrScr), becomes transparent background (at least when doing it in the PiGUI screens). 

As noted by @vakhoir [here](https://github.com/pioneerspacesim/pioneer/pull/4624#issuecomment-510613586):

> Ok, I almost figured it out. The button coloring was broken by the change in Color.h in c19aab4, and I'm still trying to get to the bottom of it, but the transparent screenshots started when #4626 was merged

Also, there's some unrelated bug with button background coloring?

**Comment by pcercuei** [comment]
The button coloring issue was fixed in #4640.

**Comment by impaktor** [comment]
Ah, OK, updated title to only be about this one bug (screenshot backgrounds).

**Comment by impaktor** [comment]
Not sure I've seen this lately. Might be fixed? 
Note to self: test

**Comment by Web-eWorks** [comment]
It's only the in-game dump-screen-to-png keybind that's affected - the background of the pigui screens is cleared to a transparent color and before I reworked a lot of the UI colors most of the elements on that screen were using transparent colors. Should be better now, but not completely fixed if I had to guess.

**Comment by nozmajner** [comment]
Not sure if its related to this but I noticed that on newer builds (2023 dec) the thruster plumes and star halos create transparent artifacts on native screenshots, when there's a star behind. And the solar halo even adds an alpha channel to the png.
Seems like it does not affect the billboard landing lights, although it might just not be that noticable.

Noticed first on screenhots by Какое-то_имя from Discord.
![image](https://github.com/pioneerspacesim/pioneer/assets/4182678/89743867-0b14-4050-91b5-86121b4a03bb)
![image](https://github.com/pioneerspacesim/pioneer/assets/4182678/b5293544-ab74-489e-a692-3e2108c69957)
![image](https://github.com/pioneerspacesim/pioneer/assets/4182678/c49ffe4e-c245-4c7b-9765-553063456f23)

It is present in #5617 too, but on other recent builds without this feature as well.

In-game these artifacts aren't visible.
