### ISSUE TITLE
NPC ships stuck at orbital starport

### ISSUE THREAD

**Issue by maxso-216** [pioneerspacesim/pioneer#5830]
### Observed behaviour

Multiple NPC ships stuck at the orbital starport and create huge lag. Also, it is not possible to land in the spaceport.

![Screenshot from 2024-04-26 23-52-29](https://github.com/pioneerspacesim/pioneer/assets/107261566/35bd1822-70d7-4c30-8195-39485e6b0b28)

![Screenshot from 2024-04-26 23-52-45](https://github.com/pioneerspacesim/pioneer/assets/107261566/377c74d5-391b-44ac-b59b-d57387178154)

The collision effect is also offset-ed, but I believe this is another bug that is fixed in newer version.

### Expected behaviour

No NPC ships should be stucked.

### Steps to reproduce

As it is happened randomly(?), I do not know exact steps to reproduce.

__My pioneer version (and OS):__

20240203 (via flatpak), Ubuntu 23.10

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/pioneerspacesim/pioneer/files/15132782/output.txt)

save file : https://shota.nu/ss/ybf8tjpd.gz

**Comment by impaktor** [comment]
I believe this was fixed in the 3.14 release, by multiple NPS ship fixes:
https://github.com/pioneerspacesim/pioneer/releases/tag/20240314

@Gliese852 I assume we can close this?

**Comment by Gliese852** [comment]
@impaktor I'm not sure, I don't think I've encountered such a problem, need to check.

**Comment by impaktor** [comment]
@maxso-216 Please use the latest release (3.14), to load your old saves, you might have to hold down Ctrl to force load them, the first time.

**Comment by maxso-216** [comment]
@impaktor I tried with latest release and recover the save file. Seems like the situation still exists. 

![Screenshot from 2024-04-27 20-44-03](https://github.com/pioneerspacesim/pioneer/assets/107261566/7ac554d2-dc24-4822-a2c6-f11dbbf040a6)

Haven't tried going to other systems and see if same thing happen again, maybe report later.

**Comment by maxso-216** [comment]
@impaktor I build from source code and play for 2 hours, and same thing happen again. Its very lag that I can't fly close to it.

![Screenshot from 2024-04-28 00-30-16](https://github.com/pioneerspacesim/pioneer/assets/107261566/5a10f7ca-e0ef-40ae-8be5-e98ba3f6a35d)

save file:https://shota.nu/r5akwxcl.gz


[output.txt](https://github.com/pioneerspacesim/pioneer/files/15138970/output.txt)

**Comment by impaktor** [comment]
@maxso-216 Yeah, if this still happens in new systems in 2024.3.14 release or master it makes it very much more interesting.

I assume you've spent a long time in the same system for this problem to emerge, e.g. doing many inter-planetary missions?

**Comment by maxso-216** [comment]
@impaktor I don't travel the same system for a long time. In fact, I travel different systems and doing missions. The bug happen as I travel to another system and try to dock to an orbital starport to find some missions to do. As the game getting leggy when the ship approaching the starport, I know the bug happens again.

 Interestingly, the bug happens quite randomly as I don't encounter same thing when approaching orbital starport in previous system. Maybe long gameplay time cause the bug?

**Comment by impaktor** [comment]
@maxso-216 If you want to gain further understanding of the bug, pull up the debug window (Ctrl+i) and check the "Trade Ships"-tab, and see if you notice a pattern for when the bug is there vs. when it's not there.

**Comment by maxso-216** [comment]
@impaktor After some observations, I have come up with a threom.

The bug is caused when an orbital star-port refuses to allow anyone to dock for no reason.

![Screenshot from 2024-04-29 09-59-44](https://github.com/pioneerspacesim/pioneer/assets/107261566/0d28b431-88ae-422e-aea1-53ee7cbd41cc)

As shown above, my ship's autopilot stuck at this position and refuses to dock. Even entering the station manually doesn't work. Its pretty odd that I have landing permission. So, I stay at far position and observe for hours.

![Screenshot from 2024-04-29 10-24-08](https://github.com/pioneerspacesim/pioneer/assets/107261566/9aa24435-30bc-4401-9bb6-7729393a1b6d)

So, few hours pass and a NPC starship come. It stuck at this position. Worth my waiting. I have checked the debug menu but it shows nothing special.

Thus, I wait for another NPC ship to arrive. However this time, they collide and unstuck(?), somehow they manage to dock, so as my ship, which is different from what I except. However, I believe this is the root cause of the bug, as with large number of ship simulating when traveling to different systems, the problematic star-port will cause a jam, resulting this bug. Maybe I was wrong, but this is the best guessing I can come up with.

**Comment by bszlrd** [comment]
I encountered this one again. Ships are stuck inside each other at the entrance, constantly colliding.
And the frame isn't set to the station either. Maybe this is part of thecause, or just an effect of the ship getting stuck? All the previous screenshots show that too.
Landing on the station is not possible. Docking permission is granted, but the capture does not happen, the ship clips through the station.

I was in the system for an in-game day and a half at least, took a quick courier mission, then a SAR, from which I was heading back. That one took about a day. The station is rather close to the star, 0.17 AU or so, ships arrive quite quickly. I was seeing one arriving just about when I approached the station for example, but there were collisions happeing then already.

I'm on the shield update branch, but I think it is unrelated to that, but might be intersting for the save I'm attaching.
[Petrichor III SAR error not-json](https://github.com/user-attachments/files/16248058/Petrichor.III.SAR.error.json)
[output.txt](https://github.com/user-attachments/files/16248109/output.txt)
[Video of station approach and failed docking](https://youtu.be/3Qjucqz7q-Q)
![screenshot-20240716-135737](https://github.com/user-attachments/assets/640e3c46-b721-47cc-827c-864df3f4a88f)
![image](https://github.com/user-attachments/assets/ecd0c56b-05f2-492b-95e5-201ea6d9f1a1)
![screenshot-20240716-135744](https://github.com/user-attachments/assets/635b7545-8f73-4868-ad2c-15394139e2aa)
